name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    env:
      BUILD_TYPE: Release
      CONAN_LOG_LEVEL: warning
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python (for Conan)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Conan
        run: python -m pip install --disable-pip-version-check --quiet conan
      - name: Conan profile detect
        run: conan profile detect --force -v${{ env.CONAN_LOG_LEVEL }}
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.23.0'
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4
      - name: Build and export ng-log
        run: |
          conan create conan/recipes/ng-log --version=0.8.2 --build=missing -s build_type=${{ env.BUILD_TYPE }} -v${{ env.CONAN_LOG_LEVEL }}
      - name: Conan install
        run: conan install conanfile.py --output-folder=build/conan --build=missing -s build_type=${{ env.BUILD_TYPE }} -v${{ env.CONAN_LOG_LEVEL }}
      - name: Configure CMake (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: cmake --preset conan-default -DBUILD_TESTS=ON
      - name: Configure CMake (Non-Windows)
        if: ${{ runner.os != 'Windows' }}
        run: cmake --preset conan-release -DBUILD_TESTS=ON
      - name: Build (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: cmake --build build/conan/build --config ${{ env.BUILD_TYPE }}
      - name: Build (Non-Windows)
        if: ${{ runner.os != 'Windows' }}
        run: cmake --build --preset conan-release
      - name: Run tests (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: ctest --test-dir build/conan/build --build-config ${{ env.BUILD_TYPE }} --output-on-failure
      - name: Run tests (Non-Windows)
        if: ${{ runner.os != 'Windows' }}
        run: ctest --preset conan-release --output-on-failure
